# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\UCU\POC\PSoC_Projects_Embedded\PSoC_LAB4\lab6-psoc-3-shevchuk-lykhanskyi\Lab_4_1_BLE_Automation_IO.cydsn\Lab_4_1_BLE_Automation_IO.cyprj
# Date: Tue, 09 Dec 2025 12:28:09 GMT
#set_units -time ns
create_clock -name {CapSense_ModClk(FFB)} -period 5312.5 -waveform {0 2656.25} [list [get_pins {ClockBlock/ff_div_5}]]
create_clock -name {CapSense_SnsClk(FFB)} -period 5312.5 -waveform {0 2656.25} [list [get_pins {ClockBlock/ff_div_4}]]
create_clock -name {ADC_SAR_intClock(FFB)} -period 437.5 -waveform {0 218.75} [list [get_pins {ClockBlock/ff_div_6}]]
create_clock -name {UART_DEB_SCBCLK(FFB)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CapSense_ModClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {CapSense_SnsClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {ADC_SAR_intClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 21 43} [list]
create_generated_clock -name {UART_DEB_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 27 53} -nominal_period 541.66666666666663 [list]
create_generated_clock -name {SPIM_IntClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 7 13} [list [get_pins {ClockBlock/udb_div_1}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 961 1921} [list [get_pins {ClockBlock/udb_div_3}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for D:\UCU\POC\PSoC_Projects_Embedded\PSoC_LAB4\lab6-psoc-3-shevchuk-lykhanskyi\Lab_4_1_BLE_Automation_IO.cydsn\TopDesign\TopDesign.cysch
# Project: D:\UCU\POC\PSoC_Projects_Embedded\PSoC_LAB4\lab6-psoc-3-shevchuk-lykhanskyi\Lab_4_1_BLE_Automation_IO.cydsn\Lab_4_1_BLE_Automation_IO.cyprj
# Date: Tue, 09 Dec 2025 12:28:06 GMT
